create table address
(
    id     bigserial
        primary key,
    city   varchar(255),
    street varchar(255)
);

alter table address
    owner to postgres;

create table company
(
    id   bigint generated by default as identity
        primary key,
    name varchar(255)
);

alter table company
    owner to postgres;

create table department
(
    department_id     bigserial
        primary key,
    department_name   varchar(255) not null,
    address_id        bigint
        constraint fk7jumubp4ks3jmgkvxuglx3x6x
            references address,
    department_status varchar(255)
        constraint department_department_status_check
            check ((department_status)::text = ANY
        (ARRAY [('PENDING'::character varying)::text, ('APPROVED'::character varying)::text, ('REJECTED'::character varying)::text])),
    company_id        bigint
        constraint fkh1m88q0f7sc0mk76kju4kcn6f
            references company
);

alter table department
    owner to postgres;

create table employee
(
    id         bigint generated by default as identity
        primary key,
    email      varchar(255),
    first_name varchar(255),
    last_name  varchar(255),
    position   varchar(255),
    salary     integer
);

alter table employee
    owner to postgres;

create table company_employee
(
    company_id  bigint not null
        constraint fkrtmqwiubff604xe2osnxdgoqe
            references company,
    employee_id bigint not null
        constraint fkmn18hg3oma19jvhrip11s5cm
            references employee,
    primary key (company_id, employee_id)
);

alter table company_employee
    owner to postgres;

